### ISSUE TITLE
Order numbers increasing by 3 instead of 1

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-advanced-sequential-order-numbers#11]
We've now had two reports of this happening. Due to the changes in #2, order numbers are skipping 3 each time. It goes 2, 5, 8, instead of 2, 3, 4.

**Comment by pippinsplugins** [comment]
This is happening due to the use of `edd_payment_saved`, which is firing multiple times when a payment is created.

**Comment by pippinsplugins** [comment]
@sunnyratilal could you tackle this please>

**Comment by pippinsplugins** [comment]
Report here https://secure.helpscout.net/conversation/500563095/73619?folderId=180499

**Comment by pippinsplugins** [comment]
Another report https://secure.helpscout.net/conversation/500238917/73586?folderId=180499

**Comment by pippinsplugins** [comment]
Another report https://secure.helpscout.net/conversation/503297522/73895?folderId=180499

**Comment by sunnyratilal** [comment]
I think the best way to fix this is by reverting the changes introduced in #2 as the changes made in EDD Recurring did fix the issue initially.

**Comment by pippinsplugins** [comment]
:+1:
